//! Submodule implementing the `orbitals` method for the `Element` enum.

use super::{AtomicOrbital, AtomicOrbitalType};

const H_ORBITALS: &[AtomicOrbital] = &[AtomicOrbital::new(1, AtomicOrbitalType::S, 1)];
const HE_ORBITALS: &[AtomicOrbital] = &[AtomicOrbital::new(1, AtomicOrbitalType::S, 2)];
const LI_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 1),
];
const BE_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
];
const B_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 1),
];
const C_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 2),
];
const N_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 3),
];
const O_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 4),
];
const F_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 5),
];
const NE_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
];
const NA_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 1),
];
const MG_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
];
const AL_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 1),
];
const SI_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 2),
];
const P_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 3),
];
const S_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 4),
];
const CL_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 5),
];
const AR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
];
const K_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 1),
];
const CA_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
];
const SC_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
];
const TI_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
];
const V_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 3),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
];
const CR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 5),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 1),
];
const MN_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 5),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
];
const FE_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
];
const CO_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 7),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
];
const NI_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 8),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
];
const CU_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 1),
];
const ZN_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
];
const GA_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 1),
];
const GE_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 2),
];
const AS_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 3),
];
const SE_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 4),
];
const BR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 5),
];
const KR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
];
const RB_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 1),
];
const SR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
];
const Y_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
];
const ZR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
];
const NB_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 4),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 1),
];
const MO_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 5),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 1),
];
const TC_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 5),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
];
const RU_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 7),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 1),
];
const RH_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 8),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 1),
];
const PD_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
];
const AG_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 1),
];
const CD_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
];
const IN_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 1),
];
const SN_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 2),
];
const SB_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 3),
];
const TE_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 4),
];
const I_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 5),
];
const XE_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
];
const CS_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 1),
];
const BA_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const LA_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const CE_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 1),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const PR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 3),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const ND_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 4),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const PM_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 5),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const SM_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const EU_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 7),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const GD_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 7),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const TB_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 9),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const DY_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const HO_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 11),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const ER_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 12),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const TM_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 13),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const YB_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const LU_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const HF_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const TA_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 3),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const W_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 4),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const RE_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 5),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const OS_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const IR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 7),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const PT_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 9),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 1),
];
const AU_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 1),
];
const HG_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
];
const TL_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 1),
];
const PB_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 2),
];
const BI_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 3),
];
const PO_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 4),
];
const AT_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 5),
];
const RN_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
];
const FR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 1),
];
const RA_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const AC_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const TH_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 2),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const PA_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const U_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 3),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const NP_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 4),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const PU_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const AM_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 7),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const CM_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 7),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 1),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const BK_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 9),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const CF_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 10),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const ES_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 11),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const FM_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 12),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const MD_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 13),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const NO_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const LR_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(7, AtomicOrbitalType::P, 1),
];
const RF_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 2),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const DB_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 3),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const SG_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 4),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const BH_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 5),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const HS_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 6),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const MT_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 7),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const DS_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 8),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const RG_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 9),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const CN_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
];
const NH_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(7, AtomicOrbitalType::P, 1),
];
const FL_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(7, AtomicOrbitalType::P, 2),
];
const MC_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(7, AtomicOrbitalType::P, 3),
];
const LV_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(7, AtomicOrbitalType::P, 4),
];
const TS_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(7, AtomicOrbitalType::P, 5),
];
const OG_ORBITALS: &[AtomicOrbital] = &[
    AtomicOrbital::new(1, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(2, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(3, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(3, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(4, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(4, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(4, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(5, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(5, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(5, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(5, AtomicOrbitalType::F, 14),
    AtomicOrbital::new(6, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(6, AtomicOrbitalType::P, 6),
    AtomicOrbital::new(6, AtomicOrbitalType::D, 10),
    AtomicOrbital::new(7, AtomicOrbitalType::S, 2),
    AtomicOrbital::new(7, AtomicOrbitalType::P, 6),
];

impl crate::Element {
    #[must_use]
    #[allow(clippy::too_many_lines)]
    /// Returns the orbitals associated to the element.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use elements_rs::{AtomicOrbitalType, Element};
    ///
    /// let orbitals = Element::H.orbitals();
    /// assert_eq!(orbitals.len(), 1);
    /// assert_eq!(orbitals[0].orbital_type(), AtomicOrbitalType::S);
    /// assert_eq!(orbitals[0].number_of_electrons(), 1);
    /// ```
    pub fn orbitals(&self) -> &'static [AtomicOrbital] {
        match self {
            Self::H => H_ORBITALS,
            Self::He => HE_ORBITALS,
            Self::Li => LI_ORBITALS,
            Self::Be => BE_ORBITALS,
            Self::B => B_ORBITALS,
            Self::C => C_ORBITALS,
            Self::N => N_ORBITALS,
            Self::O => O_ORBITALS,
            Self::F => F_ORBITALS,
            Self::Ne => NE_ORBITALS,
            Self::Na => NA_ORBITALS,
            Self::Mg => MG_ORBITALS,
            Self::Al => AL_ORBITALS,
            Self::Si => SI_ORBITALS,
            Self::P => P_ORBITALS,
            Self::S => S_ORBITALS,
            Self::Cl => CL_ORBITALS,
            Self::Ar => AR_ORBITALS,
            Self::K => K_ORBITALS,
            Self::Ca => CA_ORBITALS,
            Self::Sc => SC_ORBITALS,
            Self::Ti => TI_ORBITALS,
            Self::V => V_ORBITALS,
            Self::Cr => CR_ORBITALS,
            Self::Mn => MN_ORBITALS,
            Self::Fe => FE_ORBITALS,
            Self::Co => CO_ORBITALS,
            Self::Ni => NI_ORBITALS,
            Self::Cu => CU_ORBITALS,
            Self::Zn => ZN_ORBITALS,
            Self::Ga => GA_ORBITALS,
            Self::Ge => GE_ORBITALS,
            Self::As => AS_ORBITALS,
            Self::Se => SE_ORBITALS,
            Self::Br => BR_ORBITALS,
            Self::Kr => KR_ORBITALS,
            Self::Rb => RB_ORBITALS,
            Self::Sr => SR_ORBITALS,
            Self::Y => Y_ORBITALS,
            Self::Zr => ZR_ORBITALS,
            Self::Nb => NB_ORBITALS,
            Self::Mo => MO_ORBITALS,
            Self::Tc => TC_ORBITALS,
            Self::Ru => RU_ORBITALS,
            Self::Rh => RH_ORBITALS,
            Self::Pd => PD_ORBITALS,
            Self::Ag => AG_ORBITALS,
            Self::Cd => CD_ORBITALS,
            Self::In => IN_ORBITALS,
            Self::Sn => SN_ORBITALS,
            Self::Sb => SB_ORBITALS,
            Self::Te => TE_ORBITALS,
            Self::I => I_ORBITALS,
            Self::Xe => XE_ORBITALS,
            Self::Cs => CS_ORBITALS,
            Self::Ba => BA_ORBITALS,
            Self::La => LA_ORBITALS,
            Self::Ce => CE_ORBITALS,
            Self::Pr => PR_ORBITALS,
            Self::Nd => ND_ORBITALS,
            Self::Pm => PM_ORBITALS,
            Self::Sm => SM_ORBITALS,
            Self::Eu => EU_ORBITALS,
            Self::Gd => GD_ORBITALS,
            Self::Tb => TB_ORBITALS,
            Self::Dy => DY_ORBITALS,
            Self::Ho => HO_ORBITALS,
            Self::Er => ER_ORBITALS,
            Self::Tm => TM_ORBITALS,
            Self::Yb => YB_ORBITALS,
            Self::Lu => LU_ORBITALS,
            Self::Hf => HF_ORBITALS,
            Self::Ta => TA_ORBITALS,
            Self::W => W_ORBITALS,
            Self::Re => RE_ORBITALS,
            Self::Os => OS_ORBITALS,
            Self::Ir => IR_ORBITALS,
            Self::Pt => PT_ORBITALS,
            Self::Au => AU_ORBITALS,
            Self::Hg => HG_ORBITALS,
            Self::Tl => TL_ORBITALS,
            Self::Pb => PB_ORBITALS,
            Self::Bi => BI_ORBITALS,
            Self::Po => PO_ORBITALS,
            Self::At => AT_ORBITALS,
            Self::Rn => RN_ORBITALS,
            Self::Fr => FR_ORBITALS,
            Self::Ra => RA_ORBITALS,
            Self::Ac => AC_ORBITALS,
            Self::Th => TH_ORBITALS,
            Self::Pa => PA_ORBITALS,
            Self::U => U_ORBITALS,
            Self::Np => NP_ORBITALS,
            Self::Pu => PU_ORBITALS,
            Self::Am => AM_ORBITALS,
            Self::Cm => CM_ORBITALS,
            Self::Bk => BK_ORBITALS,
            Self::Cf => CF_ORBITALS,
            Self::Es => ES_ORBITALS,
            Self::Fm => FM_ORBITALS,
            Self::Md => MD_ORBITALS,
            Self::No => NO_ORBITALS,
            Self::Lr => LR_ORBITALS,
            Self::Rf => RF_ORBITALS,
            Self::Db => DB_ORBITALS,
            Self::Sg => SG_ORBITALS,
            Self::Bh => BH_ORBITALS,
            Self::Hs => HS_ORBITALS,
            Self::Mt => MT_ORBITALS,
            Self::Ds => DS_ORBITALS,
            Self::Rg => RG_ORBITALS,
            Self::Cn => CN_ORBITALS,
            Self::Nh => NH_ORBITALS,
            Self::Fl => FL_ORBITALS,
            Self::Mc => MC_ORBITALS,
            Self::Lv => LV_ORBITALS,
            Self::Ts => TS_ORBITALS,
            Self::Og => OG_ORBITALS,
        }
    }
}
